<h1 class="transaction_h1">Knižní přehled</h1>
<div class="flexbox">
    <?php foreach ($library as $book): ?>
        <div class="box">
            <div class="bookname"><?= $book->getName(); ?></div>
            <div class="author"><?= $book->getAuthor(); ?></div>
            <div class="year"><?= $book->getYear(); ?></div>
            <div class="details">
                <div class="anotation"><?= $book->getAnotation(); ?></div>
                <div class="score"><?= $book->getScore(); ?></div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
